language: python
python:
  - "3.7"
cache: false
dist: xenial

install:
  - wget -nv http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $PWD/miniconda
  - source $PWD/miniconda/etc/profile.d/conda.sh
  - conda config --add channels conda-forge
  - conda create --yes -n my-analysis-env python=3.7 jupyterlab ipython matplotlib uproot numpy pandas scikit-learn scipy tensorflow xgboost hep_ml
  - conda activate my-analysis-env
  # FIXME: Inline math is broken in upstream recommonmark
  - pip install git+https://github.com/chrisburr/recommonmark.git@patch-1
  - pip install starterkit-ci

script:
  - starterkit_ci build
  - starterkit_ci check

# With instructions from http://www.steveklabnik.com/automatically_update_github_pages_with_travis_example/
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && starterkit_ci deploy

env:
  global:
    secure: "S+3Gu4EZXl6pOkoy93wo5RB3qawI+TEThIOCutyQCk3gwNw3s2QBgVzqTol6plzdi2JfhNpELE9KJovEqBr9RWK7eD7k0TJcw+PJzFaVEi/iV0ZpjYyTg2ttmAGTTPz382LuXeO+4L0GB3GYIVXN5P6waHppV6D8vPbqUARl/INaj6o/ik5Gsf1FUWSimshwECOpjuWdPQq7Ju5zoTLmnBFfubJmuXf79T4trTs5/XFCbgIC4zVLvMF6tW9XSdVSeBGQqF1QWjvMNRPorpGHj8kkaON86oEFxAN3Wnw/nfN+PKplV90XqpM1Z7kUM+vBz1jL32kbxeCYltv61CdLBzlaNaPi6F/V/jvM6ABU5g7i1BXCoBOGAdg3tzihqV8VH4vLRomCRZrp2GFpAE80ljkXcIwtAv1uNynQA5KbAVL78ocxwxlj3K100X+ZqWUtuWHJ6ZC5v3RIdyZb8m4zrvx6GAhk+5nDZauLHbCopcIPvFT2mwWkXd1dbExWP4o2190pk1CyUV5udF9B5NB1ReitVoCCgn1MTT5nWueWfsU9asSUcUZR9BqMPLQW9zXKJw9SRDeuuK6gWqWP0nze+ExOtZIabHcoJr5d+pMsbi7p+cS/JUbbFzbt9CVFjr5tYEezdlMRn91sqBE01I7VEavOxnr8/iAr7iBtBZpg6Dk="
